version: "3.9"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wppw
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db:/var/lib/mysql

  wp:
    image: wordpress:php8.2-apache
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wppw
      WORDPRESS_DB_NAME: wp
    volumes:
      - wp:/var/www/html
      - ./theme:/var/www/html/wp-content/themes/bluefast

  wpcli:
    image: wordpress:cli
    depends_on:
      - wp
    user: "33:33" # www-data
    working_dir: /var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wppw
      WORDPRESS_DB_NAME: wp
    volumes:
      - wp:/var/www/html
      - ./theme:/var/www/html/wp-content/themes/bluefast

volumes:
  db:
  wp:
